FROM volcart/vcbuilder-debian:9_v9.base
MAINTAINER Seth Parker <c.seth.parker@uky.edu>

# Install vc-deps (dynamic)
COPY vc-deps/ /vc-deps/
RUN cd /vc-deps/ \
&& mkdir -p build \
&& cd build/ \
&& cmake -GNinja -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_QT5=ON -DVCDEPS_BUILD_ZLIB=OFF -DCMAKE_INSTALL_PREFIX=/usr .. \
&& ninja \
&& cd / \
&& rm -rf /vc-deps/

# Start an interactive shell
CMD ["/bin/bash"]
