FROM volcart/vcbuilder-debian:9_v5.static
MAINTAINER Seth Parker <c.seth.parker@uky.edu>

# Install apt sources
RUN apt-get clean && apt-get -y update && \
apt-get install --fix-missing --fix-broken -y \
    libbullet-dev \
&& apt-get purge && rm -rf /var/lib/apt/lists/*

# Start an interactive shell
CMD ["/bin/bash"]
